"""add matches for users

Revision ID: 6b95d304a7fb
Revises: d9884ab7d5f0
Create Date: 2024-12-17 14:37:44.016852

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b95d304a7fb"
down_revision: Union[str, None] = "d9884ab7d5f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matchs",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("matched_user_id", sa.Integer(), nullable=False),
        sa.Column("is_mutual", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["matched_user_id"],
            ["users.id"],
            name=op.f("fk_matchs_matched_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_matchs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matchs")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("matchs")
    # ### end Alembic commands ###
