"""add CASCADE to matches

Revision ID: e36e1847b744
Revises: 996f8afd9270
Create Date: 2024-12-18 13:21:44.460080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e36e1847b744"
down_revision: Union[str, None] = "996f8afd9270"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_matchs_matched_user_id_users", "matchs", type_="foreignkey"
    )
    op.drop_constraint("fk_matchs_user_id_users", "matchs", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_matchs_user_id_users"),
        "matchs",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_matchs_matched_user_id_users"),
        "matchs",
        "users",
        ["matched_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_matchs_matched_user_id_users"), "matchs", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_matchs_user_id_users"), "matchs", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_matchs_user_id_users", "matchs", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_matchs_matched_user_id_users",
        "matchs",
        "users",
        ["matched_user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
