"""add hidden user rating

Revision ID: dc8995e00842
Revises: 8bdbfd38d57a
Create Date: 2025-08-22 08:39:40.685043

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc8995e00842"
down_revision: str | None = "8bdbfd38d57a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("rating", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "rating")
    # ### end Alembic commands ###
