"""test

Revision ID: 63c404d9de48
Revises: 761fb99593eb
Create Date: 2025-04-29 13:36:30.276335

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63c404d9de48"
down_revision: str | None = "761fb99593eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "photo", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "photo", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
