"""refactor interests

Revision ID: 8bdbfd38d57a
Revises: 63c404d9de48
Create Date: 2025-08-19 13:36:28.993342

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8bdbfd38d57a"
down_revision: str | None = "63c404d9de48"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interests",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interests")),
    )
    op.create_index(op.f("ix_interests_name"), "interests", ["name"], unique=True)
    op.create_table(
        "user_interests",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("interest_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interest_id"],
            ["interests.id"],
            name=op.f("fk_user_interests_interest_id_interests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_interests_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "interest_id", name=op.f("pk_user_interests")
        ),
    )
    op.drop_column("users", "interest")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "interest",
            postgresql.ENUM("SPORTS", "MUSIC", "ART", "OTHER", name="interestenum"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_table("user_interests")
    op.drop_index(op.f("ix_interests_name"), table_name="interests")
    op.drop_table("interests")
    # ### end Alembic commands ###
