"""add name, surname, location

Revision ID: 761fb99593eb
Revises: fbe8e7b83af7
Create Date: 2025-02-18 16:46:22.216675

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "761fb99593eb"
down_revision: str | None = "fbe8e7b83af7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("first_name", sa.String(), nullable=False))
    op.add_column("users", sa.Column("last_name", sa.String(), nullable=False))
    op.add_column("users", sa.Column("location", sa.String(), nullable=False))
    op.alter_column(
        "users", "photo", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column("users", "age", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "age", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "users", "photo", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_column("users", "location")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
